# Generated by Django 5.2.17 on 2026-08-19 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMINISTRADOR", "Administrador"),
                            ("EMPLEADO", "Empleado"),
                            ("CLIENTE", "Cliente"),
                        ],
                        default="EMPLEADO",
                        max_length=20,
                    ),
                ),
                ("es_propietario", models.BooleanField(default=False)),
                ("intentos_fallidos", models.PositiveSmallIntegerField(default=0)),
                ("fecha_desbloqueo", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles",
                        to="core.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Perfiles",
                "db_table": "perfil",
            },
        ),
        migrations.CreateModel(
            name="TokenRecuperacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("expira", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_recuperacion",
                        to="cuentas.perfil",
                    ),
                ),
            ],
            options={
                "db_table": "token_recuperacion",
            },
        ),
    ]
