# Generated by Django 5.2.17 on 2026-08-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificacion_entrega_pendiente'),
        ('cuentas', '0006_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='rol_empresa_nombre_unicos'),
        ),
    ]
