# Generated by Django 5.2.17 on 2026-08-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_rol_empresa_alter_rol_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='core.empresa'),
        ),
    ]
