# Generated by Django 5.2.17 on 2026-08-27 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_carrito_empresa_alter_cliente_empresa_and_more'),
        ('cuentas', '0008_alter_perfil_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='perfil',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de Ciudadania'), ('NIT', 'NIT'), ('CE', 'Cedula de Extranjeria'), ('PAS', 'Pasaporte')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['empresa', 'rol'], name='perfil_empresa_rol_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='perfil_empresa_documento_unico'),
        ),
    ]
