# Generated by Django 5.2.17 on 2026-09-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_actividadusuario_act_usuario_fecha_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLoginFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_intentofallido', to='cuentas.perfil')),
            ],
            options={
                'unique_together': {('email', 'perfil')},
            },
        ),
    ]
