# Generated by Django 5.2.17 on 2026-09-16 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_verificar_email_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actividadusuario',
            index=models.Index(fields=['usuario', '-fecha'], name='actividad_usuario_fecha_idx'),
        ),
    ]
