# Generated by Django 5.2.17 on 2026-08-25 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cupon_carrito_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('cufe', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/pdf/')),
                ('xml', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/xml/')),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('enviado_correo', models.BooleanField(default=False)),
                ('enviado_correo_en', models.DateTimeField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_electronica', to='core.venta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('cufe_nota', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='notas_credito/%Y/%m/pdf/')),
                ('xml', models.FileField(blank=True, null=True, upload_to='notas_credito/%Y/%m/xml/')),
                ('reverso_stock', models.BooleanField(default=False)),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='core.venta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
