# Generated by Django 5.2.17 on 2026-08-27 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dashboard_vistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IAConversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada')], default='activa', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversaciones IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IAMensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=20)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error')], default='ok', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.iaconversacion')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversacion', 'created_at'], name='core_iamens_convers_e05b90_idx')],
            },
        ),
    ]
