# Generated by Django 5.2.17 on 2026-08-27 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_iaconversacion_iamensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=150)),
                ('url_stream', models.CharField(blank=True, default='', max_length=300)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('ninguno', 'Sin entrega'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('resuelta', 'Resuelta')], default='nueva', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('stock', 'Stock bajo'), ('factura', 'Facturacion'), ('camara', 'Camara'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['empresa', 'estado'], name='core_notifi_empresa_929c3e_idx'),
        ),
        migrations.AddField(
            model_name='camara',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='camara',
            index=models.Index(fields=['empresa', 'activa'], name='core_camara_empresa_010581_idx'),
        ),
    ]
