# Generated by Django 5.2.17 on 2026-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_camara_notificacion_canal_notificacion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='entrega_pendiente',
            field=models.BooleanField(default=False, help_text='True si se intento notificar pero fallo la entrega por todos los canales y queda pendiente de reintento.'),
        ),
    ]
