# Generated by Django 5.2.17 on 2026-08-27 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Rama B: dependia de '0013_alter_venta_numero_factura_and_more' (tip de
    # la rama A) solo para forzar un grafo lineal. Su parent real es 0009:
    # todas sus operaciones (carrito/cliente.empresa nullable, indice de
    # notificacion) dependen de campos presentes desde 0008/0001. El merge
    # core/0014 concilia ambas ramas.
    dependencies = [
        ('core', '0009_notificacion_entrega_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['empresa', 'leida'], name='core_notifi_empresa_540056_idx'),
        ),
    ]
