# Generated by Django 5.2.17 on 2026-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_carrito_empresa_alter_cliente_empresa_and_more'),
        ('core', '0013_alter_venta_numero_factura_and_more'),
    ]

    operations = [
    ]
