# Generated by Django 5.2.17 on 2026-09-01 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_ramas_0010_slug_y_0010_carrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'nombre'], name='core_client_empresa_9b9d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'estado', '-fecha'], name='venta_empresa_estado_fecha_idx'),
        ),
    ]
