# Generated by Django 5.2.17 on 2026-09-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comentarioproducto'),
        ('core', '0015_cliente_core_client_empresa_9b9d7e_idx_and_more'),
    ]

    operations = [
    ]
