# Generated by Django 5.2.17 on 2026-09-03 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=80)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('transportadora', models.CharField(blank=True, max_length=80)),
                ('numero_guia', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de preparacion'), ('preparando', 'Preparando pedido'), ('despachado', 'Despachado'), ('en_transito', 'En transito'), ('entregado', 'Entregado'), ('no_entregado', 'Intento fallido'), ('devuelto', 'Devuelto al vendedor')], default='pendiente', max_length=20)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='core.venta')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='core_envio_estado_cac139_idx'), models.Index(fields=['numero_guia'], name='core_envio_numero__589c42_idx')],
            },
        ),
    ]
