# Generated by Django 5.2.17 on 2026-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reversado', 'Reversado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='pagado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pasarela',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='transaccion_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
