# Generated by Django 5.2.17 on 2026-09-09 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('archivo', models.CharField(max_length=500)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='core.camara')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['camara', 'fecha'], name='core_grabac_camara__0e4ecc_idx')],
                'constraints': [models.UniqueConstraint(fields=('camara', 'fecha', 'hora'), name='unica_grabacion_camara_fecha_hora')],
            },
        ),
    ]
