# Generated by Django 5.2.17 on 2026-09-03 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_venta_estado_pago_venta_pagado_en_venta_pasarela_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotencia_clave', models.CharField(max_length=64, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('transaccion_id', models.CharField(blank=True, default='', max_length=100)),
                ('pasarela', models.CharField(blank=True, default='', max_length=30)),
                ('respuesta_cruda', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='core_intent_usuario_987349_idx')],
            },
        ),
    ]
