# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_intentopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='intento_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.intentopago'),
        ),
    ]
