# Generated by Django 5.2.17 on 2026-09-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_envio'),
        ('core', '0020_venta_intento_pago'),
    ]

    operations = [
    ]
