# Generated by Django 5.2.17 on 2026-09-17 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_grabacion_intentopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recibos/%Y/%m/')),
                ('enviado_a', models.EmailField(blank=True, default='', max_length=254)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('error_envio', models.CharField(blank=True, default='', max_length=255)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='core.venta')),
            ],
            options={
                'db_table': 'recibo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venta'], name='recibo_venta_i_6e5042_idx')],
            },
        ),
    ]
