# Generated by Django 5.2.17 on 2026-10-06 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_documentos_privados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['producto', 'venta'], name='detventa_prod_venta_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'tipo'], name='mov_prod_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'categoria'], name='prod_emp_activo_cat_idx'),
        ),
    ]
